<a href="https://colab.research.google.com/github/nhanmai001-ct1/TH_DeepLearning/blob/main/tensorflow_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
import tensorflow as tf

# Tensor scalar (0 chiều)

# mặc định int32
rank_0_tensor = tf.constant(4)

print(rank_0_tensor)

# chỉ định kiểu dữ liệu
r1 = tf.constant(9, tf.int16)
print(r1)

r1_float = tf.constant(1.12, tf.float32)
print(r1_float)

r1_string = tf.constant(
    'Hello Vanlang University',
    tf.string
)

print(r1_string)

# Tensor 1 chiều (vector)

rank_1_tensor = tf.constant([2.0, 3.0, 4.0])

print(rank_1_tensor)

# Tensor 2 chiều (matrix)

rank_2_tensor = tf.constant(
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ],
    dtype=tf.float16
)

print(rank_2_tensor)


# Tensor 3 chiều


rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]],

    [[10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19]],

    [[20, 21, 22, 23, 24],
     [25, 26, 27, 28, 29]]
])

print(rank_3_tensor)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Vanlang University', shape=(), dtype=string)
tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)
tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)
tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


các thuộc tính

In [ ]:
import tensorflow as tf

rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]],

    [[10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19]],

    [[20, 21, 22, 23, 24],
     [25, 26, 27, 28, 29]]
])

print(rank_3_tensor)

print('shape:', rank_3_tensor.shape)

print('type of tensor:', rank_3_tensor.dtype)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
shape: (3, 2, 5)
type of tensor: <dtype: 'int32'>


 tensor tự động gán giá trị 0 ban đầu

In [ ]:
import tensorflow as tf

# Tensor 1 chiều toàn số 0

t_zero = tf.zeros(10)

print(t_zero)

# Tensor 2 chiều toàn số 0

t_2_zero = tf.zeros([3, 3])

print(t_2_zero)

# Tensor 3 chiều toàn số 0

t_3_zero = tf.zeros([3, 3, 5])

print(t_3_zero)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 3, 5), dtype=float32)


sinh số ngẫu nhiên theo phân phối chuẩn

In [ ]:
import tensorflow as tf

# Tensor ngẫu nhiên 1 chiều

range_tensor = tf.random.normal([5])

print(range_tensor)

# Tensor ngẫu nhiên 2 chiều

range_tensor = tf.random.normal([3, 3])

print(range_tensor)

tf.Tensor([ 0.66204333  0.3173418   0.67388946 -1.7911502  -0.30758443], shape=(5,), dtype=float32)
tf.Tensor(
[[ 0.5961202  -0.2759455   0.09756678]
 [ 0.32330322  0.659624   -0.42811358]
 [ 2.19446     0.09782586 -0.55814874]], shape=(3, 3), dtype=float32)


BÀI TẬP 1: Tạo một tensor có kích thước [2, 3] với các phần tử được gán 0

In [ ]:
import tensorflow as tf

tensor_zero = tf.zeros([2, 3])

print(tensor_zero)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


BÀI TẬP 2: Cho X = [[1, 2, 3], [4, 5, 6]], hãy tạo tensor có kích thước và dtype như X với các phần tử được
gán 0

In [ ]:
import tensorflow as tf

X = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])

# tạo tensor cùng shape và dtype như X
tensor_zero = tf.zeros_like(X)

print(tensor_zero)

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


BÀI TÂP 3: Tạo một tensor có kích thước [3, 2] với các phần tử được gán 5

In [ ]:
import tensorflow as tf

tensor_five = tf.fill([3, 2], 5)

print(tensor_five)

tf.Tensor(
[[5 5]
 [5 5]
 [5 5]], shape=(3, 2), dtype=int32)


BÀI TẬP 4: Tạo một tensor 1-chiều với 50 phần tử chẵn trong khoảng [5, 10]

In [ ]:
import tensorflow as tf

tensor = tf.linspace(5.0, 10.0, 50)

print(tensor)

tf.Tensor(
[ 5.         5.102041   5.2040815  5.3061223  5.408163   5.5102043
  5.612245   5.714286   5.8163266  5.9183674  6.020408   6.122449
  6.2244897  6.3265305  6.4285717  6.5306125  6.632653   6.734694
  6.836735   6.9387755  7.0408163  7.1428576  7.244898   7.346939
  7.4489794  7.5510206  7.6530614  7.755102   7.857143   7.9591837
  8.061225   8.163265   8.265306   8.367347   8.469388   8.571428
  8.67347    8.775511   8.877551   8.979592   9.081633   9.183674
  9.285715   9.387755   9.489796   9.591837   9.693878   9.795918
  9.897959  10.       ], shape=(50,), dtype=float32)


BÀI TẬP 5: Cho tensor X = [[1, 2], [3, 4], [5, 6]]. Hãy shuffle X theo chiều thứ nhất (sử dụng
random_shuffle)

In [ ]:
import tensorflow as tf

X = tf.constant([
    [1, 2],
    [3, 4],
    [5, 6]
])

# shuffle theo chiều thứ nhất (shuffle các dòng)
X_shuffle = tf.random.shuffle(X)

print(X_shuffle)

tf.Tensor(
[[3 4]
 [1 2]
 [5 6]], shape=(3, 2), dtype=int32)


BÀI 6: Tạo ngẫu nhiên 2 tensor kích thước x = (3, 2) và giá trị trong khoảng [5, 10], y = (2, 3) và giá
trị [15, 20] tương ứng. Hãy giữ giá trị đường chéo của x và thực hiện x + y.

In [ ]:
import tensorflow as tf

# =========================
# Tạo tensor x kích thước (3,2)
# giá trị trong khoảng [5,10]
# =========================

x = tf.random.uniform(
    shape=(3, 2),
    minval=5,
    maxval=10,
    dtype=tf.int32
)

# =========================
# Tạo tensor y kích thước (2,3)
# giá trị trong khoảng [15,20]
# =========================

y = tf.random.uniform(
    shape=(2, 3),
    minval=15,
    maxval=20,
    dtype=tf.int32
)

print("Tensor x:\n", x)
print("Tensor y:\n", y)

# =========================
# Giữ giá trị đường chéo của x
# =========================

diag_x = tf.linalg.diag_part(x)

print("Đường chéo của x:\n", diag_x)

# =========================
# x + y
# =========================
# Vì x(3,2) và y(2,3) khác shape
# nên cần transpose y -> (3,2)
# =========================

y_t = tf.transpose(y)

result = x + y_t

print("x + transpose(y):\n", result)

Tensor x:
 tf.Tensor(
[[7 6]
 [6 5]
 [8 7]], shape=(3, 2), dtype=int32)
Tensor y:
 tf.Tensor(
[[17 17 19]
 [19 19 15]], shape=(2, 3), dtype=int32)
Đường chéo của x:
 tf.Tensor([7 5], shape=(2,), dtype=int32)
x + transpose(y):
 tf.Tensor(
[[24 25]
 [23 24]
 [27 22]], shape=(3, 2), dtype=int32)
